# -*- coding: utf-8 -*-
"""DSP_Lab.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MiSpdbK8KhL3bLeb0dQHIkm4ENhNz9oq
"""

import numpy as np
import matplotlib.pyplot as plt
n = np.arange(-12, 12, .1)


#Before sending System
# assume 1 delay
# First Iteration
first_Value2 = 0.5 *0.5 * np.cos(np.pi *(n-4))
second_Value2 = 0.5 *0.5 * np.cos(np.pi *(n-1))
y11 = np.add(first_Value2, second_Value2)

# Second Iteration

third_Value2 =  2*np.sin(np.pi *(n+2))
fourth_Value2 =  2* np.sin(np.pi *(n))
y22 = np.add(third_Value2, fourth_Value2)

y1111=np.add(y11,y22);



# After sending System

# First Iteration
first_Value = 0.5 *0.5 * np.cos(np.pi*(n-3))
second_Value = 0.5 *0.5 * np.cos(np.pi*n)
y1 = np.add(first_Value, second_Value)


# Second Iteration
third_Value =  2*np.sin(np.pi*(n+3))
fourth_Value =  2*np.sin(np.pi*(n+1))
y2 = np.add(third_Value, fourth_Value)

y2222=np.add(y1,y2);



plt.figure(figsize=(12, 8))
# plt.subplot(3,1,1)
# plt.plot(n, y1)
# plt.title("Y1 Signal Added")

# plt.subplot(3,1,2)
# plt.plot(n, y2)
# plt.title("Y2 Signal Added")

plt.subplot(3,1,3)
plt.plot(n, y1)
plt.title("Y Signal Added")

plt.grid(True)
plt.show()


# Check Varient or not
k = 2
# afterchange_y = np.roll(y1111, y2222)

if np.array_equal(y1111, y2222):
    print("NO")
else:
    print("YES")